name: OpenLibrary to HuggingFace

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"  # Mondays 09:00 UTC ≈ 4 AM US‑Central

jobs:
  process:
    strategy:
      matrix:
        include:
          - target: authors
            file: ol_dump_authors_latest.txt.gz
          - target: editions
            file: ol_dump_editions_latest.txt.gz
          - target: works
            file: ol_dump_works_latest.txt.gz
      max-parallel: 3

    runs-on: ubuntu-latest
    timeout-minutes: 360
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      HF_REPO_ID: sayshara/openlibrary

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Restore manifest cache
        uses: actions/cache@v3
        with:
          path: ol_sync_manifest.json
          key: ol-manifest-${{ runner.os }}

      - name: Install deps
        run: pip install -U pandas pyarrow huggingface_hub requests

      - name: Process ${{ matrix.target }} dump
        run: |
          python openlibrary_pipeline.py fetch --only ${{ matrix.file }} --keep
          python openlibrary_pipeline.py convert ${{ matrix.file }}
          rm -f ${{ matrix.file }}*

      - name: Save manifest cache (last writer wins)
        uses: actions/cache@v3
        with:
          path: ol_sync_manifest.json
          key: ol-manifest-${{ runner.os }}
