name: Upload OpenLibrary Dump

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install huggingface_hub requests

      - name: Run uploader
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python fetch_and_upload.py
