name: Upload OpenLibrary Dump

on:
  schedule:
    - cron: '0 5 * * *'  # Every day at 5:00 UTC
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - ol_dump_authors_latest.txt.gz
          - ol_dump_editions_latest.txt.gz
          - ol_dump_works_latest.txt.gz
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install huggingface_hub requests pandas pyarrow tqdm

      - name: Run uploader for matrix file
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "Processing file: ${{ matrix.file }}"
          python fetch_and_upload.py ${{ matrix.file }}
