name: Upload OpenLibrary Dump

on:
  schedule:
    - cron: '0 5 * * *'  # Every day at 5:00 UTC
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install huggingface_hub requests pandas pyarrow tqdm

      - name: Run uploader
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "Monitoring resource usage before running uploader..."
          top -b -n 1
          python fetch_and_upload.py
          echo "Monitoring resource usage after running uploader..."
          top -b -n 1
