name: Sequential OL Upload

on:
  workflow_dispatch:

jobs:
  process_each_file:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - ol_dump_authors_latest.txt.gz
          - ol_dump_editions_latest.txt.gz
          - ol_dump_works_latest.txt.gz
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install tqdm requests

      - name: Download + Split + Manifest Update for ${{ matrix.file }}
        run: |
          mkdir -p gz_cache
          python process_file_once.py ${{ matrix.file }}

      - name: Upload Manifest
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install huggingface_hub huggingface-cli
          huggingface-cli upload sayshara/ol_dump             ol_sync_manifest.json metadata/ol_sync_manifest.json             --repo-type dataset --token "$HF_TOKEN"
