name: Validate OpenLibrary Workflow

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore manifest cache
        uses: actions/cache@v3
        with:
          path: ol_sync_manifest.json
          key: ol-manifest-${{ runner.os }}

      - name: Install dependencies
        run: pip install pandas pyarrow huggingface_hub requests

      - name: Dry-run fetch and upload
        run:
          python workflow/fetch_and_upload.py --dry-run

      - name: Create test fixture
        run: |
          mkdir -p test
          echo '{"type": "work", "title": "Test Work"}' > test/test_data.json
          echo '{"type": "edition", "title": "Test Edition"}' >> test/test_data.json
          gzip -f test/test_data.json

      - name: Dry-run parquet conversion
        run:
          python workflow/convert_to_parquet.py test/test_data.json.gz test/test_output --dry-run
